# This is a basic workflow to help you get started with Actions

name: SITE-CHANGED-TRIGGER

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [trigger]
  workflow_dispatch:    
jobs:
  # This workflow contains a single job called "build"
  build_deploy:
    if: github.ref == 'refs/heads/main'
    # if: "github.event.client_payload.action == 'dev-version'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: version
        run: |
            git checkout -f -b version-branch
            npm version patch --no-commit-hooks -m "$(git log -1 --pretty=%B) .... bump version [skip ci]"
            git push origin version-branch:main --follow-tags          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: kube-HPC/kube-HPC.github.io
          path: './website'
          ref: master
      - name: build
        run: |
          ls website
          docker login --username yehiyam --password ${DOCKER_HUB_PASS}
          PRIVATE_REGISTRY=docker.io/hkube npm run build
        env:
          DOCKER_HUB_PASS: ${{ secrets.DOCKER_PASSWORD }}

      


     